apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ubuntu-app
  name: ubuntu-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-demo
  template:
    metadata:
      labels:
        app: ubuntu-demo
        app.kubernetes.io/instance: ubuntu-app
    spec:
      containers:
      - image: ubuntu:latest
        name: ubuntu
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 320Mi
          requests:
            cpu: 100m
            memory: 128Mi
