apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nginx-app
  name: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
        app.kubernetes.io/instance: nginx-app
    spec:
      containers:
      - image: ajithshah/k8s-agent:lates
        imagePullPolicy: Always
        name: monitor
        resources:
          limits:
            cpu: 20m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nginx-app
  name: nginx-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-app
  type: ClusterIP