deploymentConf:
  replicaCount: 2
  appContainers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
