deploymentConf:
  appContainers:
  - image: nginx:latest
    name: nginx
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  replicaCount: 2
