command:
- sleep
image:
  pullPolicy: Always
  repository: ubuntu
  tag: latest
replicaCount: 1
resources:
  limits:
    cpu: 20m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi
service:
  port: 80
  targetPort: 80
  type: ClusterIP
